spring:
  application:
    name=helpdesk
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          descriptor:
            sql: trace
        show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
jwt-secret: aa8a1eda05ed6c1d85fa895fab690c8ee9da6146d896560a31944dccc60a0f78e9bdd0d6ae22e7d117ab04c3c7b4429df71fb6a803bc88ee7decf2cdc34cfda2